name=FileE2MMA
version=1.0.0
author=TonNom
maintainer=TonNom <ton.email@example.com>
sentence=Gère la lecture de fichiers XML depuis une clé USB avec interface graphique.
paragraph=Bibliothèque permettant de détecter une clé USB, lire des fichiers XML et les afficher via une interface graphique LVGL sur une carte GIGA R1.
category=Data Storage
url=https://github.com/toncompte/FileE2MMA
architectures=*
includes=FileE2MMA.h
